title: Artificial Intelligence on Embedded Systems
description: > # this means to ignore newlines until "baseurl:"
  A collection of articles, blog posts, discussions of latest trends in the >
  field of Artificial intelligence on Embedded Systems (Edge AI). Special focus >
  on computer vision domain and the tools, techniques, SOTAs >
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rpratesh.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Pratesh Kumar Reddy # add your name
author-img: 10672613.jpeg # add your photo
about-author: Living at the edge.. # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: rpratesh # add your Github handle
social-linkedin: http://www.linkedin.com/rpratesh # add your Linkedin handle
social-email: # add your Email address

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
